In [5]:
import pandas as pd
df= pd.read_csv('/content/indonesian_youth_digital_friction_dataset.csv')
df

     Tekanan_Ekonomi  Probabilitas_Toxic                 Status
0           0.219346            0.000739       ✅ Netral / Pasif
1           0.413012            0.013323       ✅ Netral / Pasif
2           0.976635            0.984473  🚨 Toxic (Adu Mekanik)
3           0.088899            0.000104       ✅ Netral / Pasif
4           0.479290            0.035208       ✅ Netral / Pasif
..               ...                 ...                    ...
995         0.568609            0.122296       ✅ Netral / Pasif
996         0.184474            0.000438       ✅ Netral / Pasif
997         0.472505            0.031909       ✅ Netral / Pasif
998         0.729748            0.609740  🚨 Toxic (Adu Mekanik)
999         0.413290            0.013378       ✅ Netral / Pasif

[1000 rows x 3 columns]

In [6]:
df.head()

   Tekanan_Ekonomi  Probabilitas_Toxic                 Status
0         0.219346            0.000739       ✅ Netral / Pasif
1         0.413012            0.013323       ✅ Netral / Pasif
2         0.976635            0.984473  🚨 Toxic (Adu Mekanik)
3         0.088899            0.000104       ✅ Netral / Pasif
4         0.479290            0.035208       ✅ Netral / Pasif

In [7]:
df.tail()

     Tekanan_Ekonomi  Probabilitas_Toxic                 Status
995         0.568609            0.122296       ✅ Netral / Pasif
996         0.184474            0.000438       ✅ Netral / Pasif
997         0.472505            0.031909       ✅ Netral / Pasif
998         0.729748            0.609740  🚨 Toxic (Adu Mekanik)
999         0.413290            0.013378       ✅ Netral / Pasif

In [8]:
df.columns

Index(['Tekanan_Ekonomi', 'Probabilitas_Toxic', 'Status'], dtype='object')

In [9]:
df.describe()

       Tekanan_Ekonomi  Probabilitas_Toxic
count      1000.000000         1000.000000
mean          0.508823            0.306171
std           0.286122            0.380270
min           0.000577            0.000028
25%           0.262486            0.001410
50%           0.513777            0.057688
75%           0.748901            0.675574
max           0.999832            0.988986

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Tekanan_Ekonomi     1000 non-null   float64
 1   Probabilitas_Toxic  1000 non-null   float64
 2   Status              1000 non-null   object
dtypes: float64(2), object(1)
memory usage: 23.6+ KB

In [13]:
df.shape

(1000, 3)

In [14]:
df.isnull()

     Tekanan_Ekonomi  Probabilitas_Toxic  Status
0              False               False   False
1              False               False   False
2              False               False   False
3              False               False   False
4              False               False   False
..               ...                 ...     ...
995            False               False   False
996            False               False   False
997            False               False   False
998            False               False   False
999            False               False   False

[1000 rows x 3 columns]

In [15]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [16]:
df['Status'].unique()

array(['✅ Netral / Pasif', '🚨 Toxic (Adu Mekanik)'], dtype=object)

In [17]:
df['Status'].nunique()

2